# Generated by Django 3.0.8 on 2020-07-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200722_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
